language: java
jdk:
- oraclejdk7
script: ./travis_build.sh
env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: WbbA1qEGJqeoD8pfv0O1+LaQsuEa0d9BqBEO3BcSVe+ajbnybUnFzUdweVGZAL+TkzEiA7/q8tQJgI+8VxNzhlfD0n7vFya62jK1VhZCcHA6cTS9cGDkRD0bbUdRl2Am9y1k3giSjDuMUiKetT8/fEloZKDc1R5tLi1cahzT/+w=
  - secure: XKuBU1Vx7vajHKCmwKkj7i9Z6IR6hmpD4HuOLRd1FsfgJ5YrWf0J2/CEk2mj/F13m3Fliok6AZGlJ9NeOWgylB8bMk6G2C3BpnKQrR4L5VQgQfE6EV7nyZRipQySCbISm2TkLrgwyvbzby5KoHozVdtJX/iWKpoel0LqUvOS32c=
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: repo.raymanoz.com
  region: eu-west-1
  endpoint: repo.raymanoz.com.s3-website-eu-west-1.amazonaws.com
  skip_cleanup: true
  local-dir: target/s3
  upload-dir: net/spmiller/org/lesscss/lesscss/$BUILD_NUMBER
