language: java
jdk:
- oraclejdk7
script: ./travis_build.sh
env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: UAyyiISVgcPjVXGkChjWWjeoHTFC/Zml5PfJwxoRuIsq6XgKFO4HgvETTY0p+fD85rZpYXsIHUKJWvykTJBTK7P6m81HsFNsD7rV+lJDbDId7iSTwpHiBZT8Xlhi1LbUgJZ5Ew8eP8NOjNsEuxJ6D+pKac6b/XcWa2EcA7EUpYM=
  - secure: DMEAtPoyYlMCU2woZ8m0ADFU71HlmG43q2Orf463MBDWfl2GpeEi+qZiPvJR7fodBRj0yJiTJpq9Ol1vsFtAhpSNq5iFbmwOvdb73/YoVyr7kyp/MUmj6YzfHdup79zlYYtnWJWKyVQFHp9J5eqrJ+TetGLJ5ePI0Oa8j8Bvlho=
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: repo.raymanoz.com
  region: eu-west-1
  endpoint: repo.raymanoz.com.s3-website-eu-west-1.amazonaws.com
  skip_cleanup: true
  local-dir: target/s3
  upload-dir: net/spmiller/org/lesscss/lesscss/$BUILD_NUMBER
